version: '3.8'

services:
  postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod
    healthcheck:
      test: pg_isready -U postgres
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./api/:/api/
    ports:
    - 8000:8000
    env_file:
      - ./api/api/.env.prod
    depends_on:
      - postgres
  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   command : npm start
  #   volumes:
  #     - ./web/:/usr/src/web/
  #   ports:
  #     - "3000:3000"
  nginx-api:
    image: nginx
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    # volumes:
    #   - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
    #   - static_volume:/home/api/api/staticfiles
    ports:
      - 80:80
    depends_on:
      - api
  # nginx-web:
  #   build: ./nginx/web
  #   volumes:
  #     - static_volume:/home/api/api/staticfiles
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api

volumes:
  postgres_data:
  # static_volume: