version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod
  api:
    build: ./api
    command: gunicorn.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  # web:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   command : npm start
  #   volumes:
  #     - ./web/:/usr/src/web/
  #   ports:
  #     - "3000:3000"

volumes:
  postgres_data: