version: '3.8'

services:
  postgres:
    image: postgres
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    healthcheck:
      test: pg_isready -U postgres
  api:
    platform: linux/amd64
    build:
      context: ./api
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000 
    volumes:
      - ./api/:/api/
    ports:
    - 8000:8000
    env_file:
      - ./api/api/.env.dev
    depends_on:
      - postgres

volumes:
  postgres_data: