version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/api/api/staticfiles
    expose:
      - 8000
    env_file:
      - ./nginx/.env
    depends_on:
      - postgres
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command : npm start
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - "3000:3000"
  postgres:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
  nginx-api:
    build: ./nginx/api
    volumes:
      - static_volume:/home/api/api/staticfiles
    ports:
      - 8080:80
    depends_on:
      - api
  nginx-web:
    build: ./nginx/web
    volumes:
      - static_volume:/home/api/api/staticfiles
    ports:
      - 80:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume: